/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    FrontmatterEditor: typeof import('./src/components/FrontmatterEditor.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NParagraph: typeof import('naive-ui')['NParagraph']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NTitle: typeof import('naive-ui')['NTitle']
    NTypography: typeof import('naive-ui')['NTypography']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetFrontmatter: typeof import('./src/components/SetFrontmatter.vue')['default']
    SwitchDark: typeof import('./src/components/SwitchDark.vue')['default']
    SwitchLang: typeof import('./src/components/SwitchLang.vue')['default']
  }
}
