/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    FileTree: typeof import('./src/components/FileTree.vue')['default']
    FrontmatterEditor: typeof import('./src/components/FrontmatterEditor.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetFrontmatter: typeof import('./src/components/SetFrontmatter.vue')['default']
    SwitchDark: typeof import('./src/components/SwitchDark.vue')['default']
  }
}
